anonymous namespace causes some issues with unity builds
D:\.conan\102945\1\hdps\DifferentialExpressionPlugin\src\TableModel.cpp(329,5): error C2872: 'local': ambiguous symbol [D:\.conan\102945\1\DifferentialExpressionPlugin.vcxproj]
  (compiling source file 'CMakeFiles/DifferentialExpressionPlugin.dir/Unity/unity_0_cxx.cxx')
      D:\.conan\102945\1\hdps\DifferentialExpressionPlugin\src\ProgressManager.cpp(21,11):
      could be 'local'
      D:\.conan\102945\1\hdps\DifferentialExpressionPlugin\src\TableModel.cpp(12,12):
      or       '`anonymous-namespace'::local'